/* DRIVERS */
export const GET_DRIVERS = "GET_DRIVERS"
export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS"
export const GET_DRIVERS_FAIL = "GET_DRIVERS_FAIL"

/* RECEIVERS */
export const GET_RECEIVERS = "GET_RECEIVERS"
export const GET_RECEIVERS_SUCCESS = "GET_RECEIVERS_SUCCESS"
export const GET_RECEIVERS_FAIL = "GET_RECEIVERS_FAIL"

/* SHIPPERS */
export const GET_SHIPPERS = "GET_SHIPPERS"
export const GET_SHIPPERS_SUCCESS = "GET_SHIPPERS_SUCCESS"
export const GET_SHIPPERS_FAIL = "GET_SHIPPERS_FAIL"

/* TRUCKING CUSTOMERS */
export const GET_TRUCKING_CUSTOMERS = "GET_TRUCKING_CUSTOMERS"
export const GET_TRUCKING_CUSTOMERS_SUCCESS = "GET_TRUCKING_CUSTOMERS_SUCCESS"
export const GET_TRUCKING_CUSTOMERS_FAIL = "GET_TRUCKING_CUSTOMERS_FAIL"

/* TRUCKING CUSTOMERS */
export const GET_TRUCKS = "GET_TRUCKS"
export const GET_TRUCKS_SUCCESS = "GET_TRUCKS_SUCCESS"
export const GET_TRUCKS_FAIL = "GET_TRUCKS_FAIL"


//ADD LOADS
export const ADD_NEW_LOAD = "ADD_NEW_LOAD"
export const ADD_LOAD_SUCCESS = "ADD_LOAD_SUCCESS"
export const ADD_LOAD_FAIL = "ADD_LOAD_FAIL"
