/* DRIVERS */
export const GET_DRIVERS = "GET_DRIVERS"
export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS"
export const GET_DRIVERS_FAIL = "GET_DRIVERS_FAIL"

/* RECEIVERS */
export const GET_RECEIVERS = "GET_RECEIVERS"
export const GET_RECEIVERS_SUCCESS = "GET_RECEIVERS_SUCCESS"
export const GET_RECEIVERS_FAIL = "GET_RECEIVERS_FAIL"

/* SHIPPERS */
export const GET_SHIPPERS = "GET_SHIPPERS"
export const GET_SHIPPERS_SUCCESS = "GET_SHIPPERS_SUCCESS"
export const GET_SHIPPERS_FAIL = "GET_SHIPPERS_FAIL"

/* TRUCKING CUSTOMERS */
export const GET_TRUCKING_CUSTOMERS = "GET_TRUCKING_CUSTOMERS"
export const GET_TRUCKING_CUSTOMERS_SUCCESS = "GET_TRUCKING_CUSTOMERS_SUCCESS"
export const GET_TRUCKING_CUSTOMERS_FAIL = "GET_TRUCKING_CUSTOMERS_FAIL"

/* TRUCKING CUSTOMERS */
export const GET_TRUCKS = "GET_TRUCKS"
export const GET_TRUCKS_SUCCESS = "GET_TRUCKS_SUCCESS"
export const GET_TRUCKS_FAIL = "GET_TRUCKS_FAIL"

/* USERS */
export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

/* USERS PROFILE */
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL"

//ADD LOADS
export const ADD_NEW_LOAD = "ADD_NEW_LOAD"
export const ADD_LOAD_SUCCESS = "ADD_LOAD_SUCCESS"
export const ADD_LOAD_FAIL = "ADD_LOAD_FAIL"

export const ADD_NEW_USER = "ADD_NEW_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"